### ISSUE TITLE
Broken XP Gain

### ISSUE THREAD

**Issue by Vinkuvanker** [blaxxun-boop/Cooking#1]
Whenever I cook anything, I seem to get a massive amount of XP, enough to instantly boost me to the next level in the cooking skill.
I also tested with a new character and world, with only this mod and it's requirements and the issue persists.
I'm not on the public test branch, and I use r2modman.

**Comment by blaxxun-boop** [comment]
Hey,

yup, I messed up. Will be fixed soonish, thanks for letting me know.

Cheers.
