### ISSUE TITLE
Dont work with the regular Stone oven

### ISSUE THREAD

**Issue by AnnaAndreaP** [blaxxun-boop/Cooking#10]
Hi, I very much like the cooking mod, but it doesnt work with anything that goes through the stone oven.
testet it with different modpacks.
before Mistlands it was only a small problem - but now ...

**Comment by blaxxun-boop** [comment]
I've tested that and it works fine with the stone oven. Btw, interally, the stone oven is just a glorified cooking station. So, if it works for the cooking station, it works for the stone oven, as they are basically the same, they just look different.
