### ISSUE TITLE
Food stats increase does not persist (or partially increased) after log out

### ISSUE THREAD

**Issue by cutezskatz06** [blaxxun-boop/Cooking#11]
While in game take Salad for example:

Default: 
HP: 26
Stam: 80

Cooked at Skill 100:
HP: 88
Stam: 270

After logging out:

HP: 39
Stam: 120

This applies to other food items of course. Using version 1.1.10

**Comment by blaxxun-boop** [comment]
This seems to be an issue with Extended Item Data Framework. Remove that and it works fine.
