### ISSUE TITLE
1.1.11 Error incompatable with Extended framework mod.

### ISSUE THREAD

**Issue by Eltharien** [blaxxun-boop/Cooking#12]
![image](https://user-images.githubusercontent.com/120341754/210187546-c97c8e48-345d-49ca-ada8-33e64177d47b.png)

Something changed in the latest update thats causing the mod to not load if your also using Randy Knapps Extended Data Framework which supports multiple mods.

Rolling back to 1.1.10 resolved the issue so its something in the new update causing the error.

**Comment by Eltharien** [comment]
after reading the files in the update looks like this change was planned

**Comment by blaxxun-boop** [comment]
Extended Item Data Framework is an obsolete mod, Epic Loot is the only mod that still uses it and it really shouldn't. The system the mod adds was added to vanilla in Mistlands. And Extended Item Data Framework messes up the stats on cooked food.
