### ISSUE TITLE
Newest Version incompatible with RandyKnapp Extended Item Frame Data Framework

### ISSUE THREAD

**Issue by jeusch8** [blaxxun-boop/Cooking#13]
When we updated from 1.1.10 to 1.1.11, server failed to load the latest version and threw up a could not load Cooking due to an incompatibility with Ext. Item Frame Data Framework.

**Comment by blaxxun-boop** [comment]
I know, I've added that, because Extended Item Data Framework messes with the stats of cooked food, basically randomizing them.
It's an obsolete mod anyway and no mod should use it anymore. It's functionality was added to Valheim itself with Mistlands.
