### ISSUE TITLE
[Suggestion] Option to disable perfect food or set the chance of it occurring.

### ISSUE THREAD

**Issue by AgentX2006** [blaxxun-boop/Cooking#14]
Ending up with 2-4 versions of every food (4 if I just leveled) is tedious and I'd rather give up the 10% speed buff than have all the clutter. Alternatively allow the chance for perfect food to be adjusted so I can set it to either 0 or 100%.

**Comment by blaxxun-boop** [comment]
You can disable that in the config already:

## Minimum required cooking skill level for a chance to cook perfect food. 0 is disabled
# Setting type: Int32
# Default value: 50
# Acceptable value range: From 0 to 100
Happy Required Level = 50
