### ISSUE TITLE
Cooking incompatible with other mod after update

### ISSUE THREAD

**Issue by KaoSdReapeR** [blaxxun-boop/Cooking#17]
After the update I get an error of incompatibility with ExtendedItemDataFramework (1.0.10)

Could not load [Cooking 1.1.11] because it is incompatible with: randyknapp.mods.extendeditemdataframework
That mod is used for EpicLoot.

Any way to fix this? Thanks.

**Comment by blaxxun-boop** [comment]
This would have to be fixed in Extended Item Data Framework and I doubt that it will get fixed, as they are currently in the process of deprecating that mod. Even Epic Loot won't use it anymore after the next update.

**Comment by blaxxun-boop** [comment]
FYI: I heard that you can download a test version of the next Epic Loot release that does not need EIDF anymore in Randys Discord.
