### ISSUE TITLE
Getting error on launch that 1.1.11 will not load (revisited)

### ISSUE THREAD

**Issue by Syranth** [blaxxun-boop/Cooking#18]
Receiving the following error launching the game:

[Error : BepInEx] Could not load [Cooking 1.1.11] because it is incompatible with: randyknapp.mods.extendeditemdataframework

The problem is when I posted a bug on the Extended Item Data Framework mod I was informed it was being depreciated and was directed to download the Epic Loot mod. Not sure what this is going to do for fixing the Cooking mod.

Edit: Source of depreciated comment - https://github.com/RandyKnapp/ValheimMods/issues/488

**Comment by blaxxun-boop** [comment]
Means you can remove Extended Item Data Framework and this will allow Cooking to load up again.
As I said, there is nothing I can do.

**Comment by Lime18** [comment]
> 

This is not an Extended Item Data Framework problem, I get it without using this mod
![Uploading Screenshot_20230108-062132_Discord.jpg…]()

**Comment by Lime18** [comment]
![Screenshot_20230108-062132_Discord](https://user-images.githubusercontent.com/29817277/211179102-ba1b7bfd-dafb-45d4-9427-a7665befe127.jpg)
