### ISSUE TITLE
Incompatability with extended Item Data Framework

### ISSUE THREAD

**Issue by gstrange42** [blaxxun-boop/Cooking#22]
I'm getting an error loading the latest version, it's not allowing the mod to load and saying it is incompatible with the latest version of Extended Item Data Framework.

**Comment by blaxxun-boop** [comment]
Yes, that is on purpose. If you get a message like this, the mod has been made incompatible by the mod author. Valheim Plus is a huge bully in the modding community and it needs to go.

Read https://github.com/blaxxun-boop/PassivePowers/issues/5 for more info.

**Comment by blaxxun-boop** [comment]
Btw, I just noticed that I've pasted the message under your wrong issue. Extended Item Data Framework is deprecated, you can safely remove that.
