### ISSUE TITLE
Conflicting with Epic Loot

### ISSUE THREAD

**Issue by vomika7** [blaxxun-boop/Cooking#26]
![image](https://user-images.githubusercontent.com/58232110/224887665-d0ea56ca-e569-4082-933b-ce4ee8c94747.png)
seems to be conflicting with Epic Loot plugin, probably all of randyknapps mods aswell.

**Comment by vomika7** [comment]
oh it was the Extended Item Data Framework my bad

**Comment by blaxxun-boop** [comment]
The extended item data framework has been deprecated quite some time ago. You can safely remove it, even Epic Loot doesn't use it anymore.
