### ISSUE TITLE
[Question] ValheimPlus incompatibility

### ISSUE THREAD

**Issue by radiant-ai** [blaxxun-boop/Cooking#30]
Is there any reason why this mod was marked as incompatible with ValheimPlus? Are there any specific incompatible features of the mod?
Before the incompatibility attribute was added we played with this mod and V+ together and they worked fine. Now we want to play again but we miss some features of V+ so much :(

**Comment by blaxxun-boop** [comment]
The quality of Valheim Plus is terrible. It has a lot of issues and causes a lot of issues in other mods and masks them, e.g. by hiding the huge red text you usually see, if shit hits the fan. I am sick and tired of troubleshooting issues with "my mod", just to realize it's Valheim Plus causing the issue, so all of my mods are incompatible with Valheim Plus now.

There is nothing that Valheim Plus does that cannot be found in other mods, which also happen to do it way better. Valheim Plus is a "jack of all trades, master of none" kind of thing. It's also abandoned now and kept alive by random people from the community, which upload 10 different forks of that mod, which makes things even worse.

Here are some links to help you get started:
https://github.com/AzumattDev/Valheim-Plus-Replacements
https://valheim.thunderstore.io/package/Azumatt/AzuQOL/
