### ISSUE TITLE
inventory does not open

### ISSUE THREAD

**Issue by George3321** [blaxxun-boop/Cooking#32]
![image4](https://github.com/user-attachments/assets/7cf485d9-4015-4c0d-b4cf-ab5eeeb926b6)
![image3](https://github.com/user-attachments/assets/9f076e5f-ff23-409c-925d-64e76b4a126d)
![image2](https://github.com/user-attachments/assets/1424fb95-f156-4d4c-94b0-21a01f8305a3)
![image1](https://github.com/user-attachments/assets/dbe69c21-89ec-4b3d-b69e-b02c35430642)
![image0](https://github.com/user-attachments/assets/293164f8-ee45-47fa-80f5-85c18a2f7dab)
![image](https://github.com/user-attachments/assets/df3948a9-5598-4bd6-a73d-9f18659de795)

**Comment by blaxxun-boop** [comment]
Share your log.
