### ISSUE TITLE
[Suggestion/Bug] Improving Food Stacks

### ISSUE THREAD

**Issue by MechanosG** [blaxxun-boop/Cooking#34]
There are many issues posted already, addressing food stacking problems (many over a year old), but not really making suggestions on how to fix it.

In my own experience, I really like the idea of this mod (and I love/use many other smoothbrain thunderstore skill mods), but..  one food taking up potentially 20+ slots is rough.  After running out of room in some chests with non-stacking food, I went so far as to remove the gain from food (setting it to 0 in F1), then just increased the chance of getting extra food to 50% (I believe the tooltip says vanilla is 25%), to mitigate the stacking issue while still making use of the mod.  And I'm still sometimes finding food randomly creating new stacks (probably leveled cooking or something), despite 0 bonus and same visible numbers of hp/stamina/eitr gain.  I'm not sure why this is happening.

So here are my suggestions.

- Instead of having food increase every 5 levels, I suggest using every 25 levels instead.  That way, there's only 5 possible food variances (< 25 cooking, < 50 cooking, < 75 cooking, < 100 cooking, and 100 cooking).  I think this will make inventory management much better, and mitigate most of the stacking issues.  As a side effect, the jump of 25 points should also make the difference between foods more noticeable to the player, as well.

- I would also like to suggest rounding/flooring the food gains, to the nearest whole number, instead of decimal.  As it's kinda weird having food that adds 21.3 stamina instead of just 21 (and presumably that decimal amount can't be used anyway).

- Lastly, I'd like to suggest looking into why food randomly wants to create a new stack, even when it has the same stats.  Functionally, inventory management is very restrictive in Valheim, and I keep finding myself having to leave random amounts of identical food, back at my base, to save on inventory slots.  The character I'm experiencing this on, is still leveling cooking, so maybe this is related to increasing cooking skill and something under the hood being different, despite the food being functionally the same?

All of the above, has been observed/tested via Cooking 1.2.0 from thunderstore, installed with r2modman, and tested both singleplayer and multiplayer.

**Comment by blaxxun-boop** [comment]
Increasing the stats every 5 levels is perfectly fine. It's only annoying in the beginning, while you are leveling up quickly. It does not matter later on. But could possibly be a config option. Same for the rounding.

And the cooking level is stored on the food. The stats may be identical, but the skill level it was cooked at differs. Storing the cooking level is important, so that the food can update its stats, if the config is changed.

**Comment by MechanosG** [comment]
> Increasing the stats every 5 levels is perfectly fine. It's only annoying in the beginning, while you are leveling up quickly. It does not matter later on. But could possibly be a config option. Same for the rounding.

I have to disagree.  Players spend most of their time grinding the early game.  What you're calling the beginning, is like..  100+ real life hours.  Balancing the cooking skill around players that have already beat the game and/or hit 100 cooking..  is well, you know lol.  I've spent an ungodly amount of time playing Valheim in the last couple weeks on a new server, and my cooking has only hit level 23.

But alright.  Oh well.  Thanks for the other mods, pass on this one.

**Comment by blaxxun-boop** [comment]
I didn't talk about cooking 100. But once you reach level 30 or something, it levels up so slowly that you can make several stacks of food, before it stops stacking.
