### ISSUE TITLE
Update to cooking(or Blacksmithing) broke farming

### ISSUE THREAD

**Issue by Pelgris** [blaxxun-boop/Cooking#35]
On update to the 2 smoothbrain mods Cooking and Blacksmithing the ability to farm is broken; attempts to rollback the mod by uninstall reinstall with older version result in further breakage; such as unable to open inventory, and  the item needed for planting showing as 25 wood;

**Comment by Pelgris** [comment]
![farmingfail](https://github.com/user-attachments/assets/9a858d05-a3c1-4700-a615-680d9a3f7981)
This is a screenshot of what the failure looks like;  as you can see the red is what the planting would normally look like, whereas what is over the cultivated field is the singular item; however, when attempting to plant; nothing occurs; eg, click: no plant: nor removal of seed/onion

**Comment by blaxxun-boop** [comment]
Always share your entire BepInEx log file, anything else is completely useless to debug anything. Thank you for your understanding.

**Comment by Pelgris** [comment]
[bepinexlog file.txt](https://github.com/user-attachments/files/17835871/bepinexlog.file.txt)
