### ISSUE TITLE
Stacking Issue since Mistlands update.

### ISSUE THREAD

**Issue by Raynor88** [blaxxun-boop/Cooking#6]
Since Mistlands dropped any food I craft in the cauldron won't stack even tho the stats are the same. Food, Stam & Regen are set to x2. Other than that I didn't change anything else in the mod settings. I tried uninstalling, launching the game and then reinstalling but it didn't work and with the mod uninstalled it still had (current: xx) next to the food stats.

**Comment by blaxxun-boop** [comment]
That was a bug in Blacksmithing. Make sure to update your mods.
