### ISSUE TITLE
[Suggestion] One stack of food per level is a bit...

### ISSUE THREAD

**Issue by DaveKX** [blaxxun-boop/Cooking#8]
Any way you could make it so all the food X crafted by the player Y have the same stats that this food would have if crafted with the player current skill level? If you per example installs this mod and then make like 50 black soups out of the go, you would have like 10 or more different slots of the same food with different stats xD. Awesome mod nevertheless!

**Comment by Joey121215** [comment]
The multiple stacks of the same food is quite annoying and makes this mod unusable imo, there's a version by thegreyham that sadly doesn't work anymore that didn't have this multiple stack issue, not sure if it might be worth checking out

**Comment by blaxxun-boop** [comment]
Just get the skill above level 20 and it's fine. Don't keep low level food, you will never ever use it anyway.

**Comment by Joey121215** [comment]
We use all the raw meat we have to feed our wolf pack, are you saying that after level 20 multiple stacks stop occurring?
